/*
Trying to write some sql code
*/
SELECT SALARY FROM EMPLOYEE 
ORDER BY SALARY ASC
LIMIT 1, 1;

SELECT DEPARTMENT_ID, MAX(SALARY) as MaxSalary FROM EMPLOYEE
GROUP BY DEPARTMENT_ID;

SELECT d.NAME as DEPART_NAME, MAX(e.SALARY) as MaxSalary FROM EMPLOYEE e
LEFT JOIN DEPARTMENT d
ON e.DEPARTMENT_ID = d.ID
GROUP BY d.NAME
ORDER BY d.NAME ASC;

SELECT NAME from EMPLOYEE 
WHERE SALARY BETWEEN 5 AND 7
LIMIT 1

SELECT NAME from EMPLOYEE
WHERE NAME LIKE 'M%'
LIMIT 1

SELECT NAME from EMPLOYEE
WHERE NAME ILIKE 'KOLYA'


